name: Dependabot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  merge_pr:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Build app
        run: pnpm build

      - name: Merge pr
        run: gh pr merge --squash $PR
        env:
          PR: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
